Issue 5 search entries - Cody Epstein
kepsteen/code-journal pull request #10
Opened 2024-06-05 22:31 UTC by kepsteen

Added functionality for searching through entries

![Recording 2024-06-05 at 15 31 23](https://github.com/kepsteen/code-journal/assets/118944207/b40203bb-08f2-4dcf-8abe-b82297ab3bb1)

2024-06-05 22:38 UTC, brandon-moy requested changes
Good work on the feature and how you are filtering both the title and the notes for the keyword but I feel like it take more resources to be adding and removing items than if you show and hide them.

2024-06-05 22:38 UTC, brandon-moy commented on ts/main.ts
> +});
It feels like a lot more work to delete from the DOM and then recreate entries when you are clearing the filter. Why not just toggle its visibility?

2024-06-06 16:16 UTC, kepsteen commented on ts/main.ts
> +});
![Recording 2024-06-06 at 09 15 01](https://github.com/kepsteen/code-journal/assets/118944207/5a7d8058-ee76-4f1b-990e-59afe18febe7)

2024-06-06 16:21 UTC, brandon-moy approved these changes
Great job reworking this, looks good! Approved!

2024-06-06 16:32 UTC, merged